language: android

android:
  components:
    - android-27
    - build-tools-27.0.3
    - platform-tools
    - tools

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.android/build-cache/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
