language: android

android:
  components:
    - android-27
    - build-tools-27.0.3
    - platform-tools
    - tools

script:
  - ./gradlew clean :app:testDebug

cache:
  directories:
    - $HOME/.android/build-cache/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
